
'use server';

import { getFirestore } from '@/lib/firebase';
import type { Problem } from '@/types';

/**
 * Logs an error to the 'problems' collection in Firestore.
 * If Firestore is unavailable or the logging fails, it logs to the console as a fallback.
 */
export async function logProblem(error: any, context: string, details?: Record<string, any>): Promise<void> {
    try {
        const firestore = getFirestore();
        if (!firestore) {
            console.error(`[UNLOGGED ERROR in ${context}]: Firestore is not available. Check credentials.`);
            console.error('Original Error:', error);
            return;
        }

        const problemData = {
            context,
            message: error.message || 'An unknown error occurred.',
            stack: error.stack || 'No stack trace available.',
            createdAt: new Date(),
            details: details || null,
        };

        await firestore.collection('problems').add(problemData);
    } catch (loggingError) {
        console.error(`[CRITICAL] Failed to log an error to Firestore from context: ${context}.`);
        console.error('Original Error:', error);
        console.error('Logging Error:', loggingError);
    }
}

/**
 * Retrieves a paginated list of problems from Firestore, sorted by creation date.
 */
export async function getProblems({ limit = 20, offset = 0 }: { limit?: number; offset?: number } = {}): Promise<{problems: Problem[], totalCount: number}> {
    try {
        const firestore = getFirestore();
        if (!firestore) {
            const fallbackProblem: Problem = {
                id: 'local-error-1',
                context: 'getProblems',
                message: 'Firestore is not available. Please check Firebase credentials.',
                createdAt: new Date().toISOString(),
                stack: 'This error is generated by the application because it cannot connect to Firestore. Check your .env file and ensure the Firebase project credentials are correct and the database is active.',
                details: { info: "This is a fallback error object because Firestore could not be reached." }
            };
            return { problems: [fallbackProblem], totalCount: 1 };
        }

        const problemsCollection = firestore.collection('problems');
        
        // Get total count for pagination
        const countSnapshot = await problemsCollection.count().get();
        const totalCount = countSnapshot.data().count;

        if (totalCount === 0) {
            return { problems: [], totalCount: 0 };
        }

        // Fetch the paginated documents
        const snapshot = await problemsCollection.orderBy('createdAt', 'desc').limit(limit).offset(offset).get();
        
        const problems = snapshot.docs.map(doc => {
            const data = doc.data();
            return {
                id: doc.id,
                ...data,
                createdAt: data.createdAt.toDate().toISOString(),
                details: data.details || null,
            } as Problem;
        });

        return { problems, totalCount };

    } catch (error: any) {
        console.error("Error fetching problems from Firestore:", error);
        const fallbackProblem: Problem = {
            id: 'local-error-2',
            context: 'getProblems',
            message: error.message,
            stack: error.stack,
            createdAt: new Date().toISOString(),
            details: { info: "This is a fallback error object because the getProblems function failed.", originalError: error.message }
        };
        return { problems: [fallbackProblem], totalCount: 1 };
    }
}


/**
 * Deletes all documents in the 'problems' collection.
 */
export async function clearAllProblems(): Promise<{ success: boolean; error?: string }> {
     const firestore = getFirestore();
    if (!firestore) {
        return { success: false, error: 'Firestore is not available.' };
    }

    try {
        const snapshot = await firestore.collection('problems').limit(500).get(); // Batch delete
        if (snapshot.empty) {
            return { success: true };
        }
        
        const batch = firestore.batch();
        snapshot.docs.forEach(doc => {
            batch.delete(doc.ref);
        });
        
        await batch.commit();

        // If there might be more to delete, we could recursively call this,
        // but for this app, clearing in batches of 500 should be sufficient.
        if (snapshot.size === 500) {
            console.warn("Cleared 500 problems, there may be more to clear.");
        }

        return { success: true };
    } catch (error: any) {
        // Don't try to log an error that happens while clearing logs to avoid loops.
        console.error("Failed to clear problems collection:", error);
        return { success: false, error: (error as Error).message };
    }
}
