
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  Decimal,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Public,
  getRuntime,
  skip
} = require('./runtime/index-browser.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.8.0
 * Query Engine version: 3c6e192761c0362d496ed980de936e2f3cebcd3a
 */
Prisma.prismaVersion = {
  client: "7.8.0",
  engine: "3c6e192761c0362d496ed980de936e2f3cebcd3a"
}

Prisma.PrismaClientKnownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientKnownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)};
Prisma.PrismaClientUnknownRequestError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientUnknownRequestError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientRustPanicError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientRustPanicError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientInitializationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientInitializationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.PrismaClientValidationError = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`PrismaClientValidationError is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`sqltag is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.empty = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`empty is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.join = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`join is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.raw = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`raw is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.getExtensionContext is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}
Prisma.defineExtension = () => {
  const runtimeName = getRuntime().prettyName;
  throw new Error(`Extensions.defineExtension is unable to run in this browser environment, or has been bundled for the browser (running in ${runtimeName}).
In case this error is unexpected for you, please report it in https://pris.ly/prisma-prisma-bug-report`,
)}

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes



/**
 * Enums
 */

exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
});

exports.Prisma.AccountScalarFieldEnum = {
  id: 'id',
  neupId: 'neupId',
  accountType: 'accountType',
  createdOn: 'createdOn',
  accessedOn: 'accessedOn',
  displayName: 'displayName',
  displayImage: 'displayImage',
  connectionId: 'connectionId',
  roleId: 'roleId',
  agency: 'agency',
  agent: 'agent',
  workingProfile: 'workingProfile'
};

exports.Prisma.ActivityScalarFieldEnum = {
  id: 'id',
  trackerId: 'trackerId',
  title: 'title',
  details: 'details',
  activityOn: 'activityOn',
  ipAddress: 'ipAddress'
};

exports.Prisma.PropertyScalarFieldEnum = {
  id: 'id',
  slug: 'slug',
  title: 'title',
  description: 'description',
  coverImage: 'coverImage',
  type: 'type',
  purpose: 'purpose',
  status: 'status',
  currency: 'currency',
  displayPrice: 'displayPrice',
  displayPriceUnit: 'displayPriceUnit',
  areaUnit: 'areaUnit',
  locationText: 'locationText',
  geoLocation: 'geoLocation',
  structuredLocation: 'structuredLocation',
  agency: 'agency',
  agent: 'agent',
  details: 'details',
  pricing: 'pricing',
  roadAccessDetails: 'roadAccessDetails',
  distancing: 'distancing',
  earnings: 'earnings',
  landDetails: 'landDetails',
  plots: 'plots',
  apartmentDetails: 'apartmentDetails',
  metaTags: 'metaTags',
  amenities: 'amenities',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
  isFeatured: 'isFeatured',
  isApproved: 'isApproved',
  isDeleted: 'isDeleted',
  customId: 'customId'
};

exports.Prisma.PropertyLogScalarFieldEnum = {
  id: 'id',
  propertyId: 'propertyId',
  requestedBy: 'requestedBy',
  approvedBy: 'approvedBy',
  data: 'data',
  requestedOn: 'requestedOn',
  approvedOn: 'approvedOn'
};

exports.Prisma.PropertyLinkScalarFieldEnum = {
  id: 'id',
  primaryId: 'primaryId',
  secondaryId: 'secondaryId'
};

exports.Prisma.PropertyMediaScalarFieldEnum = {
  id: 'id',
  propertyId: 'propertyId',
  type: 'type',
  url: 'url',
  alt: 'alt',
  sortOrder: 'sortOrder',
  isPrimary: 'isPrimary',
  createdAt: 'createdAt',
  isDeleted: 'isDeleted'
};

exports.Prisma.PropertyHouseDetailScalarFieldEnum = {
  propertyId: 'propertyId',
  bedrooms: 'bedrooms',
  bathrooms: 'bathrooms',
  floors: 'floors',
  kitchens: 'kitchens',
  livingRooms: 'livingRooms',
  diningRooms: 'diningRooms',
  carParkingSpots: 'carParkingSpots',
  bikeParkingSpots: 'bikeParkingSpots',
  furnished: 'furnished',
  buildYear: 'buildYear',
  area: 'area',
  facing: 'facing',
  roadAccess: 'roadAccess'
};

exports.Prisma.PropertyApartmentDetailScalarFieldEnum = {
  propertyId: 'propertyId',
  bedrooms: 'bedrooms',
  bathrooms: 'bathrooms',
  onFloor: 'onFloor',
  totalFloors: 'totalFloors',
  balconies: 'balconies',
  lifts: 'lifts',
  carParkingSpots: 'carParkingSpots',
  bikeParkingSpots: 'bikeParkingSpots',
  furnished: 'furnished',
  blockName: 'blockName',
  unitNumber: 'unitNumber',
  superArea: 'superArea',
  builtUpArea: 'builtUpArea',
  maintenanceFee: 'maintenanceFee'
};

exports.Prisma.PropertyLandDetailScalarFieldEnum = {
  propertyId: 'propertyId',
  area: 'area',
  facing: 'facing',
  roadAccess: 'roadAccess',
  plotShape: 'plotShape',
  cornerPlot: 'cornerPlot',
  waterAvailable: 'waterAvailable',
  electricityAvailable: 'electricityAvailable',
  boundaryWall: 'boundaryWall'
};

exports.Prisma.PropertyCommercialDetailScalarFieldEnum = {
  propertyId: 'propertyId',
  floor: 'floor',
  washrooms: 'washrooms',
  parkingSpots: 'parkingSpots',
  frontage: 'frontage',
  usableArea: 'usableArea',
  buildingType: 'buildingType'
};

exports.Prisma.PropertyPriceScalarFieldEnum = {
  id: 'id',
  propertyId: 'propertyId',
  for: 'for',
  currency: 'currency',
  unit: 'unit',
  price: 'price',
  priceUnit: 'priceUnit'
};

exports.Prisma.PropertyOwnerScalarFieldEnum = {
  id: 'id',
  propertyId: 'propertyId',
  ownerClientId: 'ownerClientId',
  isPrimaryOwner: 'isPrimaryOwner'
};

exports.Prisma.PropertyDocumentScalarFieldEnum = {
  id: 'id',
  propertyId: 'propertyId',
  name: 'name',
  urls: 'urls',
  sortOrder: 'sortOrder'
};

exports.Prisma.PropertyChangeScalarFieldEnum = {
  id: 'id',
  propertyId: 'propertyId',
  accountId: 'accountId',
  createdById: 'createdById',
  createdForId: 'createdForId',
  workingProfileId: 'workingProfileId',
  data: 'data',
  status: 'status',
  isApproved: 'isApproved',
  createdOn: 'createdOn',
  modifiedOn: 'modifiedOn'
};

exports.Prisma.AgencyScalarFieldEnum = {
  id: 'id',
  name: 'name',
  logoUrl: 'logoUrl',
  registeredName: 'registeredName',
  contactEmail: 'contactEmail',
  contactPhone: 'contactPhone',
  mainLocation: 'mainLocation',
  branches: 'branches',
  description: 'description',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AgencyMapScalarFieldEnum = {
  id: 'id',
  agencyAccountId: 'agencyAccountId',
  accountId: 'accountId',
  role: 'role',
  lockIn: 'lockIn'
};

exports.Prisma.AgencyAgentMapScalarFieldEnum = {
  id: 'id',
  agencyId: 'agencyId',
  agentId: 'agentId',
  status: 'status',
  isAdmin: 'isAdmin'
};

exports.Prisma.AgencyCustomizationScalarFieldEnum = {
  id: 'id',
  agencyId: 'agencyId',
  customizeFor: 'customizeFor',
  customization: 'customization',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AgentScalarFieldEnum = {
  id: 'id',
  name: 'name',
  slug: 'slug',
  location: 'location',
  registered: 'registered',
  userId: 'userId',
  email: 'email',
  phone: 'phone',
  about: 'about',
  photoUrl: 'photoUrl',
  specializations: 'specializations',
  availabilityHours: 'availabilityHours',
  timeSlotDuration: 'timeSlotDuration',
  unavailability: 'unavailability',
  agencyId: 'agencyId',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ReviewScalarFieldEnum = {
  id: 'id',
  reviewedBy: 'reviewedBy',
  rating: 'rating',
  review: 'review',
  reviewedOn: 'reviewedOn',
  response: 'response',
  responseBy: 'responseBy',
  responseOn: 'responseOn'
};

exports.Prisma.RequirementScalarFieldEnum = {
  id: 'id',
  userId: 'userId',
  minBudget: 'minBudget',
  maxBudget: 'maxBudget',
  location: 'location',
  propertyType: 'propertyType',
  purpose: 'purpose',
  urgency: 'urgency',
  requiredTime: 'requiredTime',
  paymentMethod: 'paymentMethod',
  loan: 'loan',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SavedPropertyScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  propertyId: 'propertyId',
  savedAt: 'savedAt'
};

exports.Prisma.ReactedPropertyScalarFieldEnum = {
  id: 'id',
  trackedId: 'trackedId',
  propertyId: 'propertyId',
  onType: 'onType',
  reaction: 'reaction',
  reactedAt: 'reactedAt'
};

exports.Prisma.PropertyViewScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  propertyId: 'propertyId',
  onType: 'onType',
  viewedAt: 'viewedAt',
  timeViewed: 'timeViewed',
  viewedOn: 'viewedOn'
};

exports.Prisma.BaseLeadScalarFieldEnum = {
  id: 'id',
  firstName: 'firstName',
  lastName: 'lastName',
  contact: 'contact',
  source: 'source',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ClientContactScalarFieldEnum = {
  id: 'id',
  clientId: 'clientId',
  type: 'type',
  value: 'value'
};

exports.Prisma.ClientLinkScalarFieldEnum = {
  id: 'id',
  trackerId: 'trackerId',
  clientId: 'clientId'
};

exports.Prisma.ClientLeadScalarFieldEnum = {
  id: 'id',
  clientId: 'clientId',
  type: 'type',
  requirement: 'requirement',
  priority: 'priority',
  leadOwner: 'leadOwner',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SharedLeadScalarFieldEnum = {
  id: 'id',
  clientId: 'clientId',
  type: 'type',
  requirement: 'requirement',
  priority: 'priority',
  leadOwner: 'leadOwner',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.LeadActivityScalarFieldEnum = {
  id: 'id',
  leadId: 'leadId',
  data: 'data',
  activityOn: 'activityOn',
  activityBy: 'activityBy'
};

exports.Prisma.ConversationScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  customerName: 'customerName',
  customerPhone: 'customerPhone',
  customerEmail: 'customerEmail',
  customerAvatarUrl: 'customerAvatarUrl',
  notes: 'notes',
  assignedTo: 'assignedTo',
  subject: 'subject',
  lastMessageAt: 'lastMessageAt',
  lastMessageSnippet: 'lastMessageSnippet',
  lastMessageSender: 'lastMessageSender',
  isRead: 'isRead',
  leadCategory: 'leadCategory',
  leadScore: 'leadScore',
  aiInterventionActive: 'aiInterventionActive',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MessageScalarFieldEnum = {
  id: 'id',
  conversationId: 'conversationId',
  sender: 'sender',
  text: 'text',
  timestamp: 'timestamp'
};

exports.Prisma.SiteContentScalarFieldEnum = {
  id: 'id',
  key: 'key',
  value: 'value',
  section: 'section',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.UserPreferenceScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  updatedAt: 'updatedAt',
  preferences: 'preferences',
  totalViews: 'totalViews',
  totalSaves: 'totalSaves',
  totalCalls: 'totalCalls',
  totalInquiries: 'totalInquiries',
  totalVisitRequests: 'totalVisitRequests',
  totalMortgageRequests: 'totalMortgageRequests',
  totalShares: 'totalShares',
  totalTimeSpentInSeconds: 'totalTimeSpentInSeconds'
};

exports.Prisma.PropertyRequestScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  location: 'location',
  propertyType: 'propertyType',
  bedrooms: 'bedrooms',
  bathrooms: 'bathrooms',
  budget: 'budget',
  remarks: 'remarks',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.MortgageRequestScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  address: 'address',
  age: 'age',
  income: 'income',
  moreDetails: 'moreDetails',
  contactMethods: 'contactMethods',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SalesRequestScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  propertyLocation: 'propertyLocation',
  propertyType: 'propertyType',
  remarks: 'remarks',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.VisitRequestScalarFieldEnum = {
  id: 'id',
  propertyId: 'propertyId',
  propertyTitle: 'propertyTitle',
  agentId: 'agentId',
  agentName: 'agentName',
  name: 'name',
  email: 'email',
  phone: 'phone',
  preferredDate: 'preferredDate',
  preferredTime: 'preferredTime',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.ProblemScalarFieldEnum = {
  id: 'id',
  context: 'context',
  message: 'message',
  stack: 'stack',
  details: 'details',
  createdAt: 'createdAt'
};

exports.Prisma.SitemapEntryScalarFieldEnum = {
  id: 'id',
  url: 'url',
  priority: 'priority',
  frequency: 'frequency',
  lastmod: 'lastmod',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AIModelScalarFieldEnum = {
  id: 'id',
  modelId: 'modelId',
  name: 'name',
  description: 'description',
  costPerMillionInputTokens: 'costPerMillionInputTokens',
  costPerMillionOutputTokens: 'costPerMillionOutputTokens',
  isDefault: 'isDefault',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PromptScalarFieldEnum = {
  id: 'id',
  promptText: 'promptText',
  description: 'description',
  name: 'name',
  placeholders: 'placeholders',
  model: 'model',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.WhatsAppConfigScalarFieldEnum = {
  id: 'id',
  apiToken: 'apiToken',
  phoneNumberId: 'phoneNumberId',
  accountId: 'accountId',
  webhookVerifyToken: 'webhookVerifyToken',
  updatedAt: 'updatedAt'
};

exports.Prisma.SiteDevLogSettingScalarFieldEnum = {
  id: 'id',
  enabled: 'enabled',
  updatedAt: 'updatedAt'
};

exports.Prisma.SiteDevLogEntryScalarFieldEnum = {
  id: 'id',
  requestId: 'requestId',
  source: 'source',
  method: 'method',
  path: 'path',
  statusCode: 'statusCode',
  outcome: 'outcome',
  durationMs: 'durationMs',
  summary: 'summary',
  details: 'details',
  createdAt: 'createdAt'
};

exports.Prisma.WhatsAppTemplateScalarFieldEnum = {
  id: 'id',
  name: 'name',
  category: 'category',
  language: 'language',
  body: 'body',
  status: 'status',
  isPreapproved: 'isPreapproved',
  createdAt: 'createdAt'
};

exports.Prisma.ContactSubmissionScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  subject: 'subject',
  body: 'body',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.InquiryScalarFieldEnum = {
  id: 'id',
  propertyId: 'propertyId',
  propertyTitle: 'propertyTitle',
  agentName: 'agentName',
  name: 'name',
  email: 'email',
  phone: 'phone',
  question: 'question',
  status: 'status',
  createdAt: 'createdAt'
};

exports.Prisma.TeamMemberScalarFieldEnum = {
  id: 'id',
  orgId: 'orgId',
  userId: 'userId',
  name: 'name',
  slug: 'slug',
  position: 'position',
  socialMedia: 'socialMedia',
  about: 'about',
  moreDetails: 'moreDetails',
  photoUrl: 'photoUrl',
  registered: 'registered',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.NewsletterSubscriptionScalarFieldEnum = {
  id: 'id',
  email: 'email',
  createdAt: 'createdAt'
};

exports.Prisma.FAQScalarFieldEnum = {
  id: 'id',
  question: 'question',
  answer: 'answer',
  category: 'category',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.AuthzRoleScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  appId: 'appId',
  scope: 'scope',
  acquisitionType: 'acquisitionType',
  approvalPolicy: 'approvalPolicy',
  applicableFor: 'applicableFor',
  permissions: 'permissions',
  updatedOn: 'updatedOn'
};

exports.Prisma.AccountAccessScalarFieldEnum = {
  accountId: 'accountId',
  appId: 'appId',
  roleId: 'roleId',
  updatedOn: 'updatedOn'
};

exports.Prisma.RoleCapabilityScalarFieldEnum = {
  id: 'id',
  roleId: 'roleId',
  capabilityId: 'capabilityId',
  scope: 'scope',
  denormalizedCapability: 'denormalizedCapability',
  roleName: 'roleName'
};

exports.Prisma.AuthzAccountAccessGrantScalarFieldEnum = {
  id: 'id',
  ownerAccountId: 'ownerAccountId',
  targetAccountId: 'targetAccountId',
  roleId: 'roleId',
  portfolioId: 'portfolioId'
};

exports.Prisma.AuthzAssetsAccessGrantScalarFieldEnum = {
  id: 'id',
  assetId: 'assetId',
  accountId: 'accountId',
  roleId: 'roleId',
  portfolioId: 'portfolioId',
  assetType: 'assetType'
};

exports.Prisma.CompetitorScalarFieldEnum = {
  id: 'id',
  name: 'name',
  description: 'description',
  crawlRules: 'crawlRules',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CompetitorSourceScalarFieldEnum = {
  id: 'id',
  competitorId: 'competitorId',
  type: 'type',
  value: 'value',
  createdAt: 'createdAt'
};

exports.Prisma.CompetitorPageScalarFieldEnum = {
  id: 'id',
  competitorId: 'competitorId',
  title: 'title',
  description: 'description',
  source: 'source',
  visibleHtml: 'visibleHtml',
  lastLoggedStatus: 'lastLoggedStatus',
  lastLoggedOn: 'lastLoggedOn',
  details: 'details',
  listedOn: 'listedOn',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CompetitorListingScalarFieldEnum = {
  id: 'id',
  competitorId: 'competitorId',
  competitorPageId: 'competitorPageId',
  title: 'title',
  description: 'description',
  purpose: 'purpose',
  agentName: 'agentName',
  price: 'price',
  priceBasis: 'priceBasis',
  isSold: 'isSold',
  details: 'details',
  loggedOn: 'loggedOn',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.PropertyCompetitionMapScalarFieldEnum = {
  id: 'id',
  propertyId: 'propertyId',
  competitorPropertyId: 'competitorPropertyId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.CompetitorTrackingScalarFieldEnum = {
  id: 'id',
  competitorPageId: 'competitorPageId',
  ourPropertyId: 'ourPropertyId',
  createdAt: 'createdAt'
};

exports.Prisma.IntelligenceMappingScalarFieldEnum = {
  id: 'id',
  accountId: 'accountId',
  cLocation: 'cLocation',
  cMinBudget: 'cMinBudget',
  cMaxBudget: 'cMaxBudget',
  cCompetitorId: 'cCompetitorId',
  cType: 'cType',
  cPurpose: 'cPurpose',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.IntelligenceAlertScalarFieldEnum = {
  id: 'id',
  mapId: 'mapId',
  accountId: 'accountId',
  listingId: 'listingId',
  status: 'status',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.JsonNullValueInput = {
  JsonNull: Prisma.JsonNull
};

exports.Prisma.NullableJsonNullValueInput = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull
};

exports.Prisma.QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};

exports.Prisma.JsonNullValueFilter = {
  DbNull: Prisma.DbNull,
  JsonNull: Prisma.JsonNull,
  AnyNull: Prisma.AnyNull
};
exports.PropertyType = exports.$Enums.PropertyType = {
  HOUSE: 'HOUSE',
  APARTMENT: 'APARTMENT',
  LAND: 'LAND',
  COMMERCIAL: 'COMMERCIAL'
};

exports.PropertyPurpose = exports.$Enums.PropertyPurpose = {
  SALE: 'SALE',
  RENT: 'RENT',
  LEASE: 'LEASE'
};

exports.PropertyStatus = exports.$Enums.PropertyStatus = {
  AWAITING_CREATION: 'AWAITING_CREATION',
  AWAITING_DELETION: 'AWAITING_DELETION',
  PENDING: 'PENDING',
  ACTIVE: 'ACTIVE',
  SOLD: 'SOLD',
  RENTED: 'RENTED',
  ARCHIVED: 'ARCHIVED'
};

exports.Reaction = exports.$Enums.Reaction = {
  Liked: 'Liked',
  Disliked: 'Disliked',
  Reported: 'Reported'
};

exports.LeadType = exports.$Enums.LeadType = {
  BUYER: 'BUYER',
  SELLER: 'SELLER',
  TENANT: 'TENANT',
  LANDLORD: 'LANDLORD'
};

exports.LeadPriority = exports.$Enums.LeadPriority = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  URGENT: 'URGENT'
};

exports.PropertyCompetitionStatus = exports.$Enums.PropertyCompetitionStatus = {
  VERIFIED: 'VERIFIED',
  UNVERIFIED: 'UNVERIFIED',
  DECLINED: 'DECLINED'
};

exports.Prisma.ModelName = {
  Account: 'Account',
  Activity: 'Activity',
  Property: 'Property',
  PropertyLog: 'PropertyLog',
  PropertyLink: 'PropertyLink',
  PropertyMedia: 'PropertyMedia',
  PropertyHouseDetail: 'PropertyHouseDetail',
  PropertyApartmentDetail: 'PropertyApartmentDetail',
  PropertyLandDetail: 'PropertyLandDetail',
  PropertyCommercialDetail: 'PropertyCommercialDetail',
  PropertyPrice: 'PropertyPrice',
  PropertyOwner: 'PropertyOwner',
  PropertyDocument: 'PropertyDocument',
  PropertyChange: 'PropertyChange',
  Agency: 'Agency',
  AgencyMap: 'AgencyMap',
  AgencyAgentMap: 'AgencyAgentMap',
  AgencyCustomization: 'AgencyCustomization',
  Agent: 'Agent',
  Review: 'Review',
  Requirement: 'Requirement',
  SavedProperty: 'SavedProperty',
  ReactedProperty: 'ReactedProperty',
  PropertyView: 'PropertyView',
  BaseLead: 'BaseLead',
  ClientContact: 'ClientContact',
  ClientLink: 'ClientLink',
  ClientLead: 'ClientLead',
  SharedLead: 'SharedLead',
  LeadActivity: 'LeadActivity',
  Conversation: 'Conversation',
  Message: 'Message',
  SiteContent: 'SiteContent',
  UserPreference: 'UserPreference',
  PropertyRequest: 'PropertyRequest',
  MortgageRequest: 'MortgageRequest',
  SalesRequest: 'SalesRequest',
  VisitRequest: 'VisitRequest',
  Problem: 'Problem',
  SitemapEntry: 'SitemapEntry',
  AIModel: 'AIModel',
  Prompt: 'Prompt',
  WhatsAppConfig: 'WhatsAppConfig',
  SiteDevLogSetting: 'SiteDevLogSetting',
  SiteDevLogEntry: 'SiteDevLogEntry',
  WhatsAppTemplate: 'WhatsAppTemplate',
  ContactSubmission: 'ContactSubmission',
  Inquiry: 'Inquiry',
  TeamMember: 'TeamMember',
  NewsletterSubscription: 'NewsletterSubscription',
  FAQ: 'FAQ',
  AuthzRole: 'AuthzRole',
  AccountAccess: 'AccountAccess',
  RoleCapability: 'RoleCapability',
  AuthzAccountAccessGrant: 'AuthzAccountAccessGrant',
  AuthzAssetsAccessGrant: 'AuthzAssetsAccessGrant',
  Competitor: 'Competitor',
  CompetitorSource: 'CompetitorSource',
  CompetitorPage: 'CompetitorPage',
  CompetitorListing: 'CompetitorListing',
  PropertyCompetitionMap: 'PropertyCompetitionMap',
  CompetitorTracking: 'CompetitorTracking',
  IntelligenceMapping: 'IntelligenceMapping',
  IntelligenceAlert: 'IntelligenceAlert'
};

/**
 * This is a stub Prisma Client that will error at runtime if called.
 */
class PrismaClient {
  constructor() {
    return new Proxy(this, {
      get(target, prop) {
        let message
        const runtime = getRuntime()
        if (runtime.isEdge) {
          message = `PrismaClient is not configured to run in ${runtime.prettyName}. In order to run Prisma Client on edge runtime, either:
- Use Prisma Accelerate: https://pris.ly/d/accelerate
- Use Driver Adapters: https://pris.ly/d/driver-adapters
`;
        } else {
          message = 'PrismaClient is unable to run in this browser environment, or has been bundled for the browser (running in `' + runtime.prettyName + '`).'
        }

        message += `
If this is unexpected, please open an issue: https://pris.ly/prisma-prisma-bug-report`

        throw new Error(message)
      }
    })
  }
}

exports.PrismaClient = PrismaClient

Object.assign(exports, Prisma)
