import type { Property, Agency } from '@/types';

const agencies: Record<string, Agency> = {
  skyline: { id: 'agency-1', name: 'Skyline Properties', logoUrl: 'https://placehold.co/100x40.png' },
  horizon: { id: 'agency-2', name: 'Horizon Realty', logoUrl: 'https://placehold.co/100x40.png' },
  pinnacle: { id: 'agency-3', name: 'Pinnacle Estates', logoUrl: 'https://placehold.co/100x40.png' },
};

export const properties: Property[] = [
  {
    id: 'p1',
    title: 'Modern Downtown Loft',
    description: 'A beautifully designed loft in the heart of the city, perfect for urban living. Features high ceilings, large windows, and a state-of-the-art kitchen.',
    price: 450000,
    location: 'New York, NY',
    bedrooms: 2,
    bathrooms: 2,
    area: 1200,
    type: 'Sale',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    amenities: ['Gym', 'Rooftop Terrace', 'Concierge'],
    agency: agencies.skyline,
    isFeatured: true,
  },
  {
    id: 'p2',
    title: 'Suburban Family Home',
    description: 'Spacious and welcoming family home in a quiet suburban neighborhood. Comes with a large backyard, a two-car garage, and a newly renovated interior.',
    price: 3200,
    location: 'Austin, TX',
    bedrooms: 4,
    bathrooms: 3,
    area: 2500,
    type: 'Rental',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    amenities: ['Backyard', 'Garage', 'Fireplace'],
    agency: agencies.horizon,
    isFeatured: true,
  },
  {
    id: 'p3',
    title: 'Cozy Beachfront Cottage',
    description: 'Charming cottage with direct access to the beach. Enjoy stunning ocean views from your own porch. Ideal for a serene getaway or a peaceful life by the sea.',
    price: 750000,
    location: 'Malibu, CA',
    bedrooms: 3,
    bathrooms: 2,
    area: 1500,
    type: 'Sale',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    amenities: ['Ocean View', 'Private Beach Access', 'Patio'],
    agency: agencies.pinnacle,
    isFeatured: true,
  },
  {
    id: 'p4',
    title: 'Luxury Penthouse Suite',
    description: 'Experience luxury living in this exclusive penthouse with panoramic city views, a private elevator, and premium finishes throughout.',
    price: 8500,
    location: 'Miami, FL',
    bedrooms: 3,
    bathrooms: 4,
    area: 3200,
    type: 'Rental',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    amenities: ['Pool', 'Private Elevator', 'City View'],
    agency: agencies.skyline,
    isFeatured: false,
  },
  {
    id: 'p5',
    title: 'Chic Studio Apartment',
    description: 'A stylish and compact studio in a trendy neighborhood, perfect for a single professional or student. Close to public transport and local cafes.',
    price: 1800,
    location: 'Chicago, IL',
    bedrooms: 1,
    bathrooms: 1,
    area: 500,
    type: 'Rental',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    amenities: ['Modern Kitchen', 'Walk-in Closet'],
    agency: agencies.horizon,
    isFeatured: false,
  },
  {
    id: 'p6',
    title: 'Mountain View Cabin',
    description: 'A rustic yet modern cabin nestled in the mountains. Perfect for nature lovers seeking tranquility and adventure. Features a large deck and a stone fireplace.',
    price: 350000,
    location: 'Denver, CO',
    bedrooms: 2,
    bathrooms: 1,
    area: 1000,
    type: 'Sale',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
    amenities: ['Mountain View', 'Deck', 'Fireplace'],
    agency: agencies.pinnacle,
    isFeatured: true,
  },
];
